apiVersion: v1
kind: Service
metadata:
  name: zk-service
  labels:
    app: zk-service
spec:
  ports:
  - port: 2181
    targetPort: 2181
    nodePort: 32181
    protocol: TCP
  selector:
    app: zk
  type: NodePort
