apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: solrc-ss
spec:
  selector:
    matchLabels:
      app: solrc
  serviceName: "solr-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: solrc
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: solrc-data
        persistentVolumeClaim:
          claimName: solrc-pvc
      securityContext:
        runAsUser: 8983
        fsGroup: 8983
      containers:
      - name: solr
        image: solr:latest
        volumeMounts:
        - name: solrc-data
          mountPath: /store
        command:
        - sh
        - -c
        - mkdir -p /store/data && mkdir -p /store/logs && cp /opt/solr/server/solr/solr.xml /store/data/solr.xml && docker-entrypoint.sh solr-foreground
        ports:
        - name: solr-port
          containerPort: 8983
        env:
          - name: SOLR_HOME
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: solrHome
          - name: SOLR_PORT
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: solrPort
          - name: ZK_HOST
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: zkHost
          - name: SOLR_HOST
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: solrHost
          - name: SOLR_LOGS_DIR
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: solrLogsDir
#  volumeClaimTemplates:
#  - metadata:
#      name: solrc-data
#    spec:
#      selector:
#        matchLabels:
#          app: solrc
#      storageClassName: standard-solrc
#      accessModes: [ "ReadWriteOnce" ]
#      resources:
#        requests:
#          storage: 30Gi
